transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/register.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/shift.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/mac.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/conv.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihello.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/pcihellocore_pcie_hard_ip_0_altgx_internal.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/pcihellocore_pcie_hard_ip_0.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/pcihellocore_inport.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/pcihellocore_hexport.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_txresp_cntrl.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_txavl_cntrl.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_tx_cntrl.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_tx.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_rx_resp.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_rx_cntrl.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_rx.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_p2a_addrtrans.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_cr_mailbox.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_cr_interrupt.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_cr_avalon.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_control_register.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_app.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_a2p_fixtrans.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_stif_a2p_addrtrans.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpciexpav_clksync.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpcie_rs_serdes.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpcie_pipe_interface.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpcie_pcie_reconfig_bridge.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altpcie_hip_pipen1b_qsys.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/altera_pcie_hard_ip_reset_controller.v}
vlog -vlog01compat -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/pcihellocore.v}
vlib pcihellocore
vmap pcihellocore pcihellocore
vlog -vlog01compat -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/altpciexpav_stif_cfg_status.v}
vlog -vlog01compat -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/pcihellocore_mm_interconnect_0.v}
vlog -sv -work work +incdir+C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules {C:/Users/8006421.USUARIOS/Documents/hellopci/hellopci/source/fpga/pcihello_restored/pcihellocore/synthesis/submodules/pcihellocore_irq_mapper.sv}
vlog -vlog01compat -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/altera_avalon_sc_fifo.v}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/altera_merlin_address_alignment.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/altera_merlin_burst_adapter_13_1.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/altera_merlin_master_agent.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/altera_merlin_master_translator.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/altera_merlin_traffic_limiter.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/pcihellocore_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/pcihellocore_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/pcihellocore_mm_interconnect_0_router.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/pcihellocore_mm_interconnect_0_router_001.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/pcihellocore_mm_interconnect_0_router_004.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/pcihellocore_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work pcihellocore +incdir+c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules {c:/users/8006421.usuarios/documents/hellopci/hellopci/source/fpga/pcihello_restored/db/ip/pcihellocore/submodules/pcihellocore_mm_interconnect_0_rsp_mux.sv}

